"""add transactions table

Revision ID: 044dd5cc40ce
Revises: aec587e0ddf0
Create Date: 2026-02-16 03:35:32.812003

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '044dd5cc40ce'
down_revision: Union[str, Sequence[str], None] = 'aec587e0ddf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
