"""remove timezone from timestamp

Revision ID: ec0f0f66a236
Revises: 6839334009ea
Create Date: 2026-02-16 03:58:35.043620

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'ec0f0f66a236'
down_revision: Union[str, Sequence[str], None] = '6839334009ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
